services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    environment:
      DSN: pgsql:host=database;port=5432;dbname=app;
      DB_USER: root
      DB_PASSWORD: password
    depends_on:
      - database
    ports:
      - 8080:80

  database:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: {}
